
name: hp_gym_ocr
description: Flutter OCR + Firebase
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.0
  google_ml_kit: ^0.16.3
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
